name: Wakatime Stats
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente Ã  meia-noite

jobs:
  update-charts:
    name: Update Wakatime Stats Charts
    runs-on: ubuntu-latest
    steps:
       uses: actions/checkout@v4 
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Opcional, mas recomendado
          
